{% set name = "theme-darcula" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c7855bbe13a32b705df4ae85cfb622515f5277df4092268fe3f93ebd790ac14c

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - jupyter-packaging >=0.7.9,<0.8
    - jupyterlab >=3.0.0,<4
    - nodejs
    - python {{ python_min }}
    - pip
    - setuptools >=40.8.0
  run:
    - jupyterlab >=3.0.0,<4
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/telamonian/theme-darcula
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A handsome Darcula theme for Jupyterlab.

extra:
  recipe-maintainers:
    - rvalieris
    - dhirschfeld
